version: '3.8'

services:
  big-buddy-db:
    image: postgres
    restart: always
    container_name: big-buddy-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
